itf ansible_host=178.249.69.56 ansible_ssh_user=root ansible_port=2222
#itf ansible_host=192.168.88.12 ansible_ssh_user=root
n8n ansible_host=192.168.88.100 ansible_ssh_user=root

[servers]
itf

[all]
itf
n8n
