---
- name: Display all encrypted data
  hosts: all
  tasks:
    - name: Variables
      ansible.builtin.debug:
        var: item
      loop:
        - "{{ bot_api_key }}"
        - "{{ tb_api_key }}"
        - "{{ owner }}"
        - "{{ redis_pass }}"
