---
- name: Display all encrypted data
  hosts: all
  gather_facts: false
  tasks:
    - name: Variables
      ansible.builtin.debug:
        var: item
      loop:
        - "{{ bot_name1 }}-{{ bot_api_key }}"
        - "{{ bot_name2 }}-{{ bot_api_key2 }}"
        - "{{ bot_name}}-{{ tb_api_key }}"
        - "{{ owner }}"
        - "{{ redis_pass }}"
