---
- name: Display all encrypted data
  hosts: all
  tasks:
    - name: Variables
      ansible.builtin.debug:
        var: item
      loop:
        - "{{ ai_name1 }} - {{ bot_api_key }}"
        - "{{ ai_name2 }} - {{ bot_api_key2 }}"
        - "{{ bot_names [0] }} - {{ tb_api_key }}"
        - "{{ owner }}"
        - "{{ redis_pass }}"