---
- name: Display all encrypted data
  hosts: all
  tasks:
    - name: Variables
      ansible.builtin.debug:
        var: item
      loop:
        #- "{{ ai_name_first }} - {{ bot_api_key }}"
        #- "{{ ai_name_second }} - {{ bot_api_key2 }}"
        - "{{ bot_names [0] }} - {{ tb_api_key }}"
        - "{{ owner }}"
        - "{{ redis_pass }}"